import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Nav from "@/components/Nav";
import ReduxProvider from "@/components/ReduxProvider";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <ReduxProvider>
          <ClerkProvider>
            <Header />
            <Nav />
            {children}
          </ClerkProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
